---
kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    registry:
      from_secret: DOCKER_REGISTRY
    username:
      from_secret: DOCKER_LOGIN
    password:
      from_secret: DOCKER_PASSWORD
    repo:
      from_secret: DOCKER_REPO
    tags:
      from_secret: DOCKER_TAG
    context: luasand
- name: deploy
  image: curlimages/curl:7.73.0
  environment:
    DOCKER_REPO:
      from_secret: DOCKER_REPO
    DOCKER_TAG:
      from_secret: DOCKER_TAG
    UPGRADE_WEBHOOK:
      from_secret: UPGRADE_WEBHOOK
  commands:
  - "curl -sS --fail --location --request POST $UPGRADE_WEBHOOK --header 'Content-Type: application/json' --data-raw '{ \"push_data\": { \"tag\": \"'$DOCKER_TAG'\" }, \"repository\": { \"repo_name\": \"'$DOCKER_REPO'\" } }'"
trigger:
  branch:
  - master
  